### ISSUE TITLE
Itemize environment text color

### ISSUE THREAD

**Issue by gorohovart** [bardsoftware/ace#122]
Mostly all text in an {itemize} environment is pink. I think that there no need for it(it is annoying).
I suppose that this environment should not change font color.

**Comment by dbarashev** [comment]
@yanenkoa Alex, can you look if it can be solved? I agree that all-pink is annoying. Maybe we can leave \item highlighted with e.g. bold font, and do nothing with the items text?

**Comment by yanenkoa** [comment]
@dbarashev Okay, sure.
